on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    strategy:
      matrix:
        python-version: ["3.11"]
        node-version: ["18.x", "19x", "20.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node deps
        run: |
          npm install
      - name: Do pre-commit checks (prettier, eslint, etc)
        run: |
          pre-commit run --all-files
      - name: Test with X
        run: |
          echo "FIXME: Setup unit tests"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "**/pytest*.xml"
          detailed_summary: true
          check_name: "JUnit report (local)"

  devel_shell:
    runs-on: ubuntu-latest
    steps:
      - uses: pvarki/ci@main
        with:
          dockerfile-target: devel_shell
          image-tag: rasenmaeher_ui:devel_shell
